### ISSUE TITLE
Can't seem to figure it out

### ISSUE THREAD

**Issue by Nelthalor** [DeadlyBossMods/DBM-Voicepack-Demo#1]
How exactly do I make a file to replace "BEWARE," "Run away little girl!" etc?

**Comment by henryj** [comment]
I think those are DBM default ones, which are not part of the voice pack. Probably seek DBM forum for help. Thanks.

**Comment by Nelthalor** [comment]
Alright thank you. What exactly is a part of them then?

**Comment by henryj** [comment]
The easist way is probablly to search .ogg files under DBM addon folder and replace the ones you'd like to.

**Comment by Nelthalor** [comment]
Thanks bud, appreciate the replies
