### ISSUE TITLE
Confusion with filenames.

### ISSUE THREAD

**Issue by Tga123** [DeadlyBossMods/DBM-Voicepack-Demo#2]
In "!VoiceText.txt" written some variant of filenames of sound files, but attached files has another.
E.G. string 100 in "!VoiceText.txt": "156157" => "Cleave", but "cleave.ogg" in files.
And i see "DBM-VPDemo/156157.ogg → DBM-VPDemo/cleave.ogg File renamed without changes." in one of lastest commits.
Which variant is right?

**Comment by QartemisT** [comment]
Use cleave.ogg, the file list hasn't been updated yet, I will get onto that. See the wiki page on the DBM-Retail for migration scripts for audio if you're upgrading.
